In [2]:
import pandas as pd
import pandera as pa

In [3]:
valores_ausentes = ['**','###!','####','****','*****','NULL']
df = pd.read_csv("ocorrencia.csv",parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARA DE MINAS,MG,NaN,2010-01-10,20:00:00,0

In [4]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia":pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "ocorrencia_classificacao":pa.Column(pa.String),
        "ocorrencia_cidade":pa.Column(pa.String),
        "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo":pa.Column(pa.String, nullable=True),
        "ocorrencia_dia":pa.Column(pa.DateTime),
        "ocorrencia_hora":pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes":pa.Column(pa.Int)
    }
)

In [5]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,2:30:00,0
6111,80251,80251,INCIDENTE,BELEM,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,NaN,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [6]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [7]:
df.loc[1]

codigo_ocorrencia                         40349
codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELEM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
Name: 1, dtype: object

In [8]:
df.iloc[1]

codigo_ocorrencia                         40349
codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELEM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
Name: 1, dtype: object

In [9]:
df.count()

codigo_ocorrencia           6114
codigo_ocorrencia2          6114
ocorrencia_classificacao    6114
ocorrencia_cidade           6114
ocorrencia_uf               6112
ocorrencia_aerodromo        3658
ocorrencia_dia              6114
ocorrencia_hora             6113
total_recomendacoes         6114
dtype: int64

In [10]:
#ocorrencias com mais de 10 recomendacoes
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade','total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               SAO PAULO                   11
326         RIO DE JANEIRO                   19
530              SAO PAULO                   11
727               ITAPOLIS                   11
872                 RECIFE                   23
884   SAO JOSE DOS PINHAIS                   11
1062            UBERLANDIA                   20
1972              BRASILIA                   11
2797                SANTOS                   13
3932               VITORIA                   12

In [11]:
#ocorrencia com a classificacao de incidente grave
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARA DE MINAS,MG,NaN,2010-01-10,20:00:00,0
29,39709,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0
...,...,...,...,...,...,...,...,...,...
6090,80221,80221,INCIDENTE GRAVE,MARAU,BA,SIRI,2021-07-31,13:15:00,0
6095,80228,80228,INCIDENTE GRAVE,ELDORADO DO SUL,RS,SIXE,2021-08-05,15:55:00,0
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6098,80248,80248,INCIDENTE GRAVE,CHAPADAO DO SUL,MS,SSCD,2021-08-06,20:00:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0

In [12]:
#ocorrencias com a classificao == 'INCIDENTE GRAVE' e o estado == 'SP'
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270,40270,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0
171,40620,40620,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0
219,41411,41411,INCIDENTE GRAVE,SAO PAULO,SP,SBMT,2010-06-08,19:30:00,2
297,42289,42289,INCIDENTE GRAVE,SAO PAULO,SP,SBMT,2010-07-29,20:06:00,0
314,42323,42323,INCIDENTE GRAVE,SAO JOSE DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0
...,...,...,...,...,...,...,...,...,...
5949,80056,80056,INCIDENTE GRAVE,FERNANDOPOLIS,SP,NaN,2021-04-28,11:20:00,0
6000,80114,80114,INCIDENTE GRAVE,LINS,SP,SWXQ,2021-06-05,19:43:00,0
6007,80124,80124,INCIDENTE GRAVE,SAO PAULO,SP,SBSP,2021-06-10,20:30:00,0
6081,80200,80200,INCIDENTE GRAVE,BRAGANCA PAULISTA,SP,SDVH,2021-07-25,12:25:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0

In [13]:
#ocorrencias onde a classificacao == 'INCIDENTE' ou o estado == 'SP'
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
...,...,...,...,...,...,...,...,...,...
6108,80244,80244,INCIDENTE,BRAGANCA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,2:30:00,0
6111,80251,80251,INCIDENTE,BELEM,PA,SBBE,2021-08-17,15:45:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [15]:
#ocorrencias onde a classificacao == 'INCIDENTE GRAVE' ou a classificacao == 'INCIDENTE' e estado == 'SP'
filtro1 = (df.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (df.ocorrencia_classificacao == 'INCIDENTE') 
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,SAO PAULO,SP,NaN,2010-01-15,15:00:00,0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0
...,...,...,...,...,...,...,...,...,...
6084,80234,80234,INCIDENTE,SAO PAULO,SP,SBSP,2021-07-26,13:20:00,0
6085,80208,80208,INCIDENTE,SAO PAULO,SP,SBMT,2021-07-27,19:45:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGANCA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [26]:
#ocorrencias onde a classificacao == 'INCIDENTE GRAVE' ou a classificacao == 'INCIDENTE' e estado == 'SP'
filtro1 = df.ocorrencia_classificacao.isin (['INCIDENTE GRAVE','INCIDENTE']) 
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,SAO PAULO,SP,NaN,2010-01-15,15:00:00,0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0
...,...,...,...,...,...,...,...,...,...
6084,80234,80234,INCIDENTE,SAO PAULO,SP,SBSP,2021-07-26,13:20:00,0
6085,80208,80208,INCIDENTE,SAO PAULO,SP,SBMT,2021-07-27,19:45:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGANCA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [29]:
#trazer todas as ocorrencias onde a cidade comeca com a letra == 'C'
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
20,40310,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0
...,...,...,...,...,...,...,...,...,...
6094,80225,80225,INCIDENTE,CURITIBA,PR,SBBI,2021-08-04,13:45:00,0
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6098,80248,80248,INCIDENTE GRAVE,CHAPADAO DO SUL,MS,SSCD,2021-08-06,20:00:00,0
6100,80235,80235,INCIDENTE,CORUMBA,MS,SBCR,2021-08-09,20:55:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [30]:
#trazer todas as ocorrencias onde a cidade finaliza com a letra == 'A'
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
12,40414,40414,INCIDENTE,BRASILIA,DF,SBBR,2010-01-10,3:00:00,0
14,40107,40107,ACIDENTE,GURUPA,PA,SNGU,2010-01-12,14:30:00,0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
25,39772,39772,INCIDENTE,UBERLANDIA,MG,NaN,2010-01-20,18:58:00,0
...,...,...,...,...,...,...,...,...,...
6100,80235,80235,INCIDENTE,CORUMBA,MS,SBCR,2021-08-09,20:55:00,0
6101,80237,80237,ACIDENTE,ITAPORA,MS,SSPO,2021-08-10,21:00:00,0
6102,80240,80240,INCIDENTE,GOIANIA,GO,SBNV,2021-08-10,14:15:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGANCA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0

In [32]:
#ocorrencias onde a cidade finaliza com os caracteres == 'MA'
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
408,43062,43062,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1
688,44198,44198,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0
1035,51785,51785,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0
1377,45939,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0
1401,46180,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0
2099,49113,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4
2102,48799,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0
2646,80059,80059,INCIDENTE,IVINHEMA,MS,NaN,2014-04-27,11:30:00,0
2657,51347,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0
2857,52340,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1
2951,52676,52676,ACIDENTE,TUCUMA,PA,NaN,2014-11-30,16:14:00,0
2968,52832,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0
2999,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
3042,52984,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0
3094,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0
3159,53223,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0
3173,53265,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2
3191,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0
3684,65414,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1
3727,65633,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0
3742,65694,65694,ACIDENTE,ANAMA,AM,NaN,2016-09-16,19:00:00,0
3883,66265,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0
4231,77371,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1
4279,77271,77271,ACIDENTE,TUCUMA,PA,NaN,2017-12-03,11:20:00,3
4313,77612,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0
4576,78080,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0
4987,78867,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,0:00:00,0
5071,78923,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0
5081,78782,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0
5406,79282,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0
5441,79338,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,9:40:00,0
5475,79400,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0
5759,79823,79823,ACIDENTE,IRACEMA,RR,NaN,2021-01-05,20:07:00,0
5776,79820,79820,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,9:27:00,0
5778,79830,79830,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,9:27:00,0
5861,79943,79943,INCIDENTE,IBOTIRAMA,BA,SNIT,2021-03-03,11:30:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0

In [34]:
#ocorrencias onde a cidade contem os caracteres == 'MU'
filtro = df.ocorrencia_cidade.str.contains('MU')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
98,40088,40088,ACIDENTE,UIRAMUTA,RR,NaN,2010-03-19,13:10:00,3
143,40350,40350,INCIDENTE GRAVE,UIRAMUTA,RR,NaN,2010-04-17,20:30:00,0
476,45168,45168,ACIDENTE,PORTO MURTINHO,MS,NaN,2010-11-08,18:25:00,0
591,43904,43904,INCIDENTE,SAO RAIMUNDO NONATO,PI,SNGG,2011-01-22,18:30:00,0
1147,45399,45399,INCIDENTE GRAVE,MUANA,PA,NaN,2012-01-18,17:35:00,0
1335,45912,45912,INCIDENTE GRAVE,MUCAJAI,RR,SWMV,2012-05-04,19:30:00,0
1377,45939,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0
1465,46193,46193,INCIDENTE,UIRAMUTA,RR,NaN,2012-07-23,13:20:00,0
1567,46356,46356,ACIDENTE,TAPIRAMUTA,BA,NaN,2012-09-22,15:50:00,3
2315,50314,50314,ACIDENTE,MUCUG�,BA,NaN,2013-10-22,20:06:00,7
2474,51145,51145,INCIDENTE,MUCURI,BA,SNMU,2014-01-23,17:15:00,0
2540,50810,50810,ACIDENTE,UIRAMUTA,RR,SJLO,2014-02-19,17:35:00,0
2806,52293,52293,INCIDENTE GRAVE,UIRAMUTA,RR,SWPD,2014-08-20,18:57:00,0
2821,52275,52275,ACIDENTE,MUCAJAI,RR,NaN,2014-08-28,14:40:00,0
3077,53115,53115,ACIDENTE,UIRAMUTA,RR,SJYR,2015-02-22,17:30:00,0
3191,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0
3540,65237,65237,ACIDENTE,PORTO MURTINHO,MS,SDWU,2016-02-20,14:20:00,0
3604,60983,60983,ACIDENTE,UIRAMUTA,RR,SJLO,2016-04-09,19:30:00,0
3618,65200,65200,ACIDENTE,PORTO MURTINHO,MS,NaN,2016-04-18,14:30:00,0
4047,66786,66786,ACIDENTE,UIRAMUTA,RR,NaN,2017-05-21,20:30:00,0
4056,66801,66801,ACIDENTE,MUNDO NOVO,MS,NaN,2017-05-28,19:00:00,0
4190,77502,77502,INCIDENTE GRAVE,MUCURI,BA,SNMU,2017-09-21,18:40:00,3
5400,79263,79263,ACIDENTE,NOVA MUTUM,MT,NaN,2020-04-06,9:30:00,0
5736,79799,79799,INCIDENTE,MUITOS CAPOES,RS,NaN,2020-12-21,13:30:00,0
5811,79864,79864,ACIDENTE,MUCAJAI,RR,NaN,2021-02-03,17:05:00,0
5922,80019,80019,ACIDENTE,NOVA MUTUM,MT,NaN,2021-04-12,11:00:00,0
5965,80077,80077,ACIDENTE,MUNDO NOVO,GO,NaN,2021-05-08,11:30:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0

In [35]:
#ocorrencias onde a cidade contem os caracteres == 'MU' ou 'CA'
filtro = df.ocorrencia_cidade.str.contains('MU|CA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
...,...,...,...,...,...,...,...,...,...
6089,80219,80219,INCIDENTE GRAVE,CASCAVEL,PR,NaN,2021-07-30,16:50:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6108,80244,80244,INCIDENTE,BRAGANCA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [37]:
#ocorrencias onde o ano é == 2010
filtro = df.ocorrencia_dia.dt.year == 2010
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
547,43806,43806,INCIDENTE,SAO JOSE DOS PINHAIS,PR,NaN,2010-12-28,16:02:00,0
548,43724,43724,ACIDENTE,COSMOPOLIS,SP,NaN,2010-12-29,12:00:00,0
549,43726,43726,ACIDENTE,ALEGRETE,RS,NaN,2010-12-29,10:35:00,6
550,43730,43730,INCIDENTE,VITORIA,ES,NaN,2010-12-30,18:10:00,0
551,43975,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0

In [39]:
#ocorrencias onde o ano == 2010 e mes == 12 e dia == 30
filtro_ano = df.ocorrencia_dia.dt.year == 2010
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia = df.ocorrencia_dia.dt.day == 30
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
550,43730,43730,INCIDENTE,VITORIA,ES,NaN,2010-12-30,18:10:00,0
551,43975,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0

In [44]:
#concatenar as colunas ocorrencia_dia + ocorrencia_hora em uma unica coluna 
#observando que uma é do tipo data e a outra do tipo string
#primeiro convertemos a coluna ocorrencia_dia que é data para string, assim as duas strings se juntam
#depois convertemos todo o conteudo string para data
#por ultimo jogamos a informacao dentro da nova coluna
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00

In [45]:
#ocorrencias entre os periodos 2010-01-03 03:00:00 as 2010-01-03 11:05:00
filtro1 = df.ocorrencia_dia_hora >= '2010-01-03 03:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2010-01-03 11:05:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1,40349,40349,INCIDENTE,BELEM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0,2010-01-03 03:00:00

In [46]:
#criacao de um novo dataframe com o resultado do filtro do ano de 2015 e mes 03
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro_ano & filtro_mes]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3088,53183,53183,ACIDENTE,AMAPORA,PR,NaN,2015-03-02,23:00:00,0,2015-03-02 23:00:00
3089,53120,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,2015-03-04 13:30:00
3090,53109,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,2015-03-05 13:50:00
3091,53112,53112,ACIDENTE,MOGI GUACU,SP,NaN,2015-03-06,21:00:00,0,2015-03-06 21:00:00
3092,53152,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,2015-03-10 11:30:00
3093,53167,53167,INCIDENTE,MARABA,PA,SBMA,2015-03-10,17:33:00,0,2015-03-10 17:33:00
3094,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,2015-03-10 21:35:00
3095,53149,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,2015-03-11 23:25:00
3096,53148,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,2015-03-12 12:40:00
3097,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
3098,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
3099,53238,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,2015-03-13 11:30:00
3100,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,7:20:00,0,2015-03-14 07:20:00
3101,53193,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,2015-03-14 18:00:00
3102,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,2015-03-15 18:30:00
3103,53151,53151,INCIDENTE GRAVE,MAUES,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
3104,53168,53168,INCIDENTE,PARA DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
3105,53169,53169,INCIDENTE,BELEM,PA,SBBE,2015-03-19,3:25:00,0,2015-03-19 03:25:00
3106,53165,53165,INCIDENTE GRAVE,SAO DESIDERIO,BA,NaN,2015-03-20,14:35:00,0,2015-03-20 14:35:00
3107,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
3108,53184,53184,ACIDENTE,PORTO UNIAO,SC,NaN,2015-03-22,13:44:00,0,2015-03-22 13:44:00
3109,53178,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,2015-03-23 17:15:00
3110,53182,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,2015-03-23 20:40:00
3111,53166,53166,INCIDENTE GRAVE,RIACHAO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,2015-03-24 14:45:00
3112,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
3113,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
3114,53412,53412,INCIDENTE GRAVE,MACAE,RJ,NaN,2015-03-24,16:35:00,0,2015-03-24 16:35:00
3115,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
3116,53186,53186,INCIDENTE,BRASILIA,DF,NaN,2015-03-27,14:55:00,0,2015-03-27 14:55:00
3117,53179,53179,ACIDENTE,CAIAP�NIA,GO,NaN,2015-03-28,10:30:00,0,2015-03-28 10:30:00
3118,53180,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,2015-03-28 18:52:00
3119,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
3120,53212,53212,INCIDENTE,JUNDIAI,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
3121,53213,53213,INCIDENTE,JUNDIAI,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
3122,53181,53181,ACIDENTE,COLIDER,MT,NaN,2015-03-29,20:17:00,0,2015-03-29 20:17:00
3123,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
3124,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00

In [47]:
df201503.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [53]:
#agrupar o df201503 por classificacao
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64